Polls/urls.py
from django.conf.urls import url
from django.urls import path
from . import views


app_name = 'Polls'


urlpatterns = [

    path('polls/', views.pollsIndex, name='pollsIndex'),
    url(r'^polls/(?P<question_id>[0-9]+)/$', views.details, name='details'),
    url(r'^polls/(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    url(r'^polls/(?P<question_id>[0-9]+)/votes/$', views.votes, name='votes'),
]

Polls/models.py
from django.db import models


# Create your models here.


class Questions(models.Model):
    question_text = models.CharField(max_length=200)
    published_date = models.DateTimeField('date_published')

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    question = models.ForeignKey(Questions, on_delete=models.CASCADE)

    def __str__(self):
        return self.choice_text


class LoginCredentials(models.Model):
    user_name = models.CharField(max_length=50, unique=True)
    password = models.CharField(max_length=50, unique=True)

Polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.urls import reverse
# Create your views here.
from .models import Questions


def pollsIndex(request):
    questions = Questions.objects.order_by('-published_date')
    context = {'questions': questions}
    return render(request, 'Polls/index.html', context)


def details(request, question_id):
    question = get_object_or_404(Questions, pk=question_id)
    context = {'question': question}
    return render(request, 'Polls/details.html', context)


def results(request, question_id):
    question = get_object_or_404(Questions, pk=question_id)
    context = {'question': question}
    return render(request, 'Polls/results.html', context)


def votes(request, question_id):
    question = get_object_or_404(Questions, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk= request.POST['choice'])
    except:
        context = {'question': question, 'error_message': 'Please select a choice!'}
        return render(request, 'Polls/details.html', context)
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponse('<div style="background-color: #2980b9; overflow: hidden;"><br><br><br><br><h1 style="text-align: center; font-size: 36px; color: white; ">Thank you for the vote!</h1><br><br><br><br><br><p style="text-align: center; font-size: 32px; color: white;">Have a nice day!</p><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br></div>')

templates/Polls/Base.html
<!DOCTYPE html>
{% load staticfiles %}

<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>HarishCoder</title>
        <link rel = "shortcut icon" type = "image/png" href = "https://lh3.googleusercontent.com/-4pWXftgjvLQ/XAKnTfRwkMI/AAAAAAAAFlI/tIHnV-ztarEk6UdDmDXtMbyw5Y6ZU8hvwCL0BGAs/w530-d-h742-n-rw/Logo.png">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
    </head>
    <body style="background: url('{% static 'Polls/images/background.jpg' %}') no-repeat center fixed ; background-size: cover; ">
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
            <a class="navbar-brand" href="/projects/polls/">Anon Polls</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </nav>
        <div class="container">
            <div class="jumbotron" style="background: rgba(0, 0, 0, 0.4); color: white;">
                <center><h1 class="display-3">Lets Poll!</h1></center>
                <br>
                {% block main_content %}
                {% endblock %}
                <footer style="position: fixed; bottom: 0%; right:0%; font-family: 'Caveat', cursive; font-size: larger; font-weight: bolder;">
                    <small class="container">Developed using Django</small>
                </footer>
            </div>
        </div>
    </body>
</html>

templates/Polls/details.html
{% extends 'Polls/Base.html' %}
{% block main_content %}
    <h1> {{ question.question_text }} </h1>
    <br>
    <form method="post" action="{% url 'Polls:votes' question.id %}">
        {% csrf_token %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="{{ forloop.counter }}" value="{{ choice.id }}"/>
            <label for="{{ forloop.counter }}"> {{ choice.choice_text }} </label>
            <br>
            <br>
        {% endfor %}
        <input type="submit" class="btn btn-success" value="Vote" />
        <a href="{% url 'Polls:pollsIndex' %}" role="button" class="btn btn-success">Back</a>
    </form>
{% endblock %}

templates/Polls/index.html
{% extends 'Polls/Base.html' %}
{% block main_content %}
<h2 class="">Choose a Poll!!</h2>
<br>
<br>
    {% if questions %}
        <ul>
        {% for q in questions %}
            <li> <a style="font-size: large;" href= "{% url 'Polls:details' q.id %}"> <b> {{ q.question_text }} </b> </a> </li>
        {% endfor %}
        </ul>
    {% endif %}
{% endblock %}

templates/Polls/results.html
<!DOCTYPE html>
{% load staticfiles %}

<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>HarishCoder</title>
        <link rel = "shortcut icon" type = "image/png" href = "https://lh3.googleusercontent.com/-4pWXftgjvLQ/XAKnTfRwkMI/AAAAAAAAFlI/tIHnV-ztarEk6UdDmDXtMbyw5Y6ZU8hvwCL0BGAs/w530-d-h742-n-rw/Logo.png">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
    </head>
    <body style="background: url('{% static 'Polls/images/background.jpg' %}') center fixed no-repeat ; background-size: cover; overflow-y: hidden;">
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
            <a class="navbar-brand" href="/projects/polls/">Anon Polls</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </nav>
        <div class="container">
            <div class="jumbotron" style="background: rgba(0, 0, 0, 0.4);">
                <br>
                <h1 style="color: white; text-align: center;"> {{ question.question_text }} </h1>
                <div class="list-group">
                    <ul>
                        <br>
                        {% for choice in question.choice_set.all %}
                            <li class="list-group-item d-flex justify-content-between align-items-center">{{ choice.choice_text }}
                                <span class="badge badge-primary"> {{ choice.votes }} vote{{ choice.votes|pluralize }} </span>
                            </li>
                            <br>
                        {% endfor %}
                    </ul>
                </div>
                <a href="{% url 'Polls:details' question.id  %}"> Vote Again?</a>
            </div>
        </div>
    </body>
</html>